[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_DEVELOPMENT_MODE = "false", VITE_LOG_LEVEL = "WARN" }

[context.staging]
  environment = { VITE_DEVELOPMENT_MODE = "false", VITE_LOG_LEVEL = "INFO" }

[context.deploy-preview]
  environment = { VITE_DEVELOPMENT_MODE = "true", VITE_LOG_LEVEL = "DEBUG" }

[context.branch-deploy]
  environment = { VITE_DEVELOPMENT_MODE = "true", VITE_LOG_LEVEL = "DEBUG" }

[functions]
  node_bundler = "esbuild"
  
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9